In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sla

### Eliminação Gaussiana

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1,2,3])
print(A)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [5]:
np.c_[A,b]

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [6]:
A = np.array([[2,3,-1],[4,4,-3],[2,-3,1]])
A

array([[ 2,  3, -1],
       [ 4,  4, -3],
       [ 2, -3,  1]])

In [7]:
b = np.array([5,3,-1])
b

array([ 5,  3, -1])

Vamos repetir todos os passos discutidos anteriormente:

_1. construção da matriz estendida_

In [8]:
A_b = np.c_[A,b]
A_b

array([[ 2,  3, -1,  5],
       [ 4,  4, -3,  3],
       [ 2, -3,  1, -1]])

In [9]:
A_b[1,0]

np.int64(4)

In [10]:
A_b[1] = A_b[1] - (A_b[1,0]/A_b[0,0])*A_b[0]
A_b[1]

array([ 0, -2, -1, -7])

In [11]:
A_b[2] = A_b[2] - (A_b[2,0]/A_b[0,0])*A_b[0]
A_b[2]

array([ 0, -6,  2, -6])

In [13]:
A_b

array([[ 2,  3, -1,  5],
       [ 0, -2, -1, -7],
       [ 0, -6,  2, -6]])

In [14]:
A_b[2] = A_b[2] - (A_b[2,1]/A_b[1,1])*A_b[1]
A_b[2]

array([ 0,  0,  5, 15])

In [15]:
A_b

array([[ 2,  3, -1,  5],
       [ 0, -2, -1, -7],
       [ 0,  0,  5, 15]])

In [16]:
def escalona(A,b):
    Ab = np.c_[A,b]
    n = len(A)
    for c in range(n-1):
        for l in range(c+1,n):
            Ab[l] = Ab[l] - (Ab[l,c]/Ab[c,c])*Ab[c]
    return Ab[:,:-1], Ab[:,-1]

In [17]:
print('A = \n', A)
print('\nb = ',b)

A = 
 [[ 2  3 -1]
 [ 4  4 -3]
 [ 2 -3  1]]

b =  [ 5  3 -1]


temos

In [18]:
A,b = escalona(A,b)
print('A_ = \n', A)
print('\nb_ = ',b)

A_ = 
 [[ 2  3 -1]
 [ 0 -2 -1]
 [ 0  0  5]]

b_ =  [ 5 -7 15]


que é o mesmo resultado que obtemos!

In [19]:
x = sla.solve(A,b)
x

array([1., 2., 3.])

In [20]:
print('A = \n', A)
print('\nb = ',b)

A = 
 [[ 2  3 -1]
 [ 0 -2 -1]
 [ 0  0  5]]

b =  [ 5 -7 15]


In [21]:
A_,b_ = escalona(A,b)
print('A_ = \n', A_)
print('\nb_ = ',b_)

A_ = 
 [[ 2  3 -1]
 [ 0 -2 -1]
 [ 0  0  5]]

b_ =  [ 5 -7 15]


In [22]:
A_@x

array([ 5., -7., 15.])

In [23]:
A = np.array([[1,1,1],[4,4,2],[2,1,-1]])
A

array([[ 1,  1,  1],
       [ 4,  4,  2],
       [ 2,  1, -1]])

In [24]:
b = np.array([1,2,0])
b

array([1, 2, 0])

Usando a função `escalona`, obtemos

In [25]:
A_,b_ = escalona(A,b)
print('A_ = \n', A_)
print('\nb_ = ',b_)

A_ = 
 [[                   1                    1                    1]
 [                   0                    0                   -2]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808]]

b_ =  [                   1                   -2 -9223372036854775808]


/tmp/ipykernel_47250/3801937255.py:6: RuntimeWarning: divide by zero encountered in scalar divide
  Ab[l] = Ab[l] - (Ab[l,c]/Ab[c,c])*Ab[c]
/tmp/ipykernel_47250/3801937255.py:6: RuntimeWarning: invalid value encountered in multiply
  Ab[l] = Ab[l] - (Ab[l,c]/Ab[c,c])*Ab[c]
/tmp/ipykernel_47250/3801937255.py:6: RuntimeWarning: invalid value encountered in cast
  Ab[l] = Ab[l] - (Ab[l,c]/Ab[c,c])*Ab[c]


In [26]:
A_b = np.c_[A,b]
A_b

array([[ 1,  1,  1,  1],
       [ 4,  4,  2,  2],
       [ 2,  1, -1,  0]])

In [27]:
A_b[1] = A_b[1] - (A_b[1,0]/A_b[0,0])*A_b[0]
A_b[1]

array([ 0,  0, -2, -2])

In [28]:
A_b[2] = A_b[2] - (A_b[2,0]/A_b[0,0])*A_b[0]
A_b[2]

array([ 0, -1, -3, -2])

In [29]:
A_b

array([[ 1,  1,  1,  1],
       [ 0,  0, -2, -2],
       [ 0, -1, -3, -2]])

In [30]:
v = np.array([[3,2,-4],[2,3,-1],[-4,-5,1]])
v

array([[ 3,  2, -4],
       [ 2,  3, -1],
       [-4, -5,  1]])

In [31]:
np.abs(v[1:,1])

array([3, 5])

In [32]:
p = np.abs(v[1:,1]).argmax()+1
p

np.int64(2)

In [33]:
p = np.abs(v[1:,1]).argmax()
p

np.int64(1)

In [34]:
p = np.abs(v[1:,1]).argmax() + 1
p

np.int64(2)

In [35]:
v

array([[ 3,  2, -4],
       [ 2,  3, -1],
       [-4, -5,  1]])

In [36]:
v[[0,2]] = v[[2,0]]

In [37]:
v[0,2] = v[2,0]

In [38]:
v

array([[-4, -5,  3],
       [ 2,  3, -1],
       [ 3,  2, -4]])

e a primeira e terceira linhas foram permutadas, conforme o esperado.